spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://localhost:3000'
              - 'http://localhost:3000'
              - 'http://10.10.10.72:3000'
#              - '*'
            allow-credentials: true
            allowedHeaders:
              - '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
            maxAge: 3600
            exposedHeaders:
              - 'Authorization'

      routes:
        #매수/매도 서버 (전체 Token 인증 필요)
        - id: trade-server
          uri: lb://TRADE-SERVER
          predicates:
            - Path=/api/v1/trade/**
          filters:
            - StripPrefix=3
            - AuthorizationHeaderFilter #Token 인증 필터
        #유저 인증 서버 (Token 인증 필요 X path)
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/api/v1/member/**
          filters:
            - StripPrefix=3
        #유저 인증 서버 (Token 인증 필요 O path)
#        - id: member-server
#          uri: lb://MEMBER-SERVER
#          predicates:
#            - Path=/api/v1/member/**
#          filters:
#            - StripPrefix=3
#            - AuthorizationHeaderFilter #Token 인증 필터
        - id: trade-service-swagger
          uri: lb://TRADE-SERVER
          predicates:
            - Path=/trade-server/api-docs
            - StripPrefix=1
springdoc:
  swagger-ui:
    urls[0]:
      name: 회원 서비스
      url: /trade-server/api-docs

    use-root-path: true

#springdoc:
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    config-url: /v3/api-docs/swagger-config
#    urls:
##      - url: http://localhost:59061/api-docs/json #localhost test - OK
##        name: Trade
#      - url: http://trade-server/api-docs/json #todo : service 추가 될때마다 swagger에 붙여 줘야됨.
#        name: Trade
##      - url: http://trade-server/api-docs/json
##        name: Trade
##      - url: http://trade-server/api-docs/json
##        name: Trade
##      - url: http://trade-server/api-docs/json
##        name: Trade
#  cache:
#    disabled: true

#eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URl}

#Token
JWT:
  SECRET_KEY: sldkfjsoidfjwoeir12393012809vxcv89usdfkjn1203491iu0isdfl

server:
  port: ${GATEWAY_SERVER}