spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: trade-server
          uri: lb://TRADE-SERVER
          predicates:
            - Path=/trade/**
          filters:
            - StripPrefix=1

#eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URl}

#Token
JWT:
  SECRET_KEY: sldkfjsoidfjwoeir12393012809vxcv89usdfkjn1203491iu0isdfl

server:
  port: ${GATEWAY_SERVER}