spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://screeninghumanity.shop'
              - 'https://localhost:3000'
              - 'http://localhost:3000'
              - 'http://10.10.10.72:3000'
              - 'https://screeninghumanity.store/'
            #              - '*'
            allow-credentials: true
            allowedHeaders:
              - '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
            maxAge: 3600
            exposedHeaders:
              - 'Authorization'

      routes:
        #매수/매도 서버 (전체 Token 인증 필요)
        - id: trade-server
          uri: lb://TRADE-SERVER
          predicates:
            - Path=/api/v1/trade/**
          filters:
            - StripPrefix=3
            - AuthorizationHeaderFilter #Token 인증 필터
        #유저 인증 서버 (Token 인증 필요 X path)
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/api/v1/member/**
          filters:
            - StripPrefix=3
        #유저 인증 서버 (Token 인증 필요 O path)
        #        - id: member-server
        #          uri: lb://MEMBER-SERVER
        #          predicates:
        #            - Path=/api/v1/member/**
        #          filters:
        #            - StripPrefix=3
        #            - AuthorizationHeaderFilter #Token 인증 필터
        #종목 토론방(chat) 서버
        #같은 stockitem url을 쓰는 서버가 있기 때문에, 위로 울려서 먼저 처리되도록.
        - id: stock-chat-server
          uri: lb://STOCK-CHAT-SERVER
          predicates:
            - Path=/api/v1/stockitem/chat/**
          filters:
            - StripPrefix=3
            - AuthorizationHeaderFilter #Token 인증 필터
        #차트 서버
        - id: chart-server
          uri: lb://CHART-SERVER
          predicates:
            - Path=/api/v1/stockitem/**
          filters:
            - StripPrefix=3
        #검색 서버
        - id: search-server
          uri: lb://SEARCH-SERVER
          predicates:
            - Path=/api/v1/search/**
          filters:
            - StripPrefix=3
        #결제 서버 (지갑 포함)
        - id: payment-server
          uri: lb://PAYMENT-SERVER
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - StripPrefix=3
        #알림 서버
        - id: notification-server
          uri: lb://NOTIFICATION-SERVER
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=3
            - AuthorizationHeaderFilter #Token 인증 필터


        #매수/매도 swagger
        - id: trade-server-swagger
          uri: lb://TRADE-SERVER
          predicates:
            - Path=/trade-service/api-docs/json
          filters:
            - StripPrefix=1
        #매수/매도 swagger
        - id: member-server-swagger
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-service/api-docs/json
          filters:
            - StripPrefix=1
        #Chart swagger
        - id: chart-server-swagger
          uri: lb://CHART-SERVER
          predicates:
            - Path=/chart-service/api-docs/json
          filters:
            - StripPrefix=1
        #Search swagger
        - id: search-server-swagger
          uri: lb://SEARCH-SERVER
          predicates:
            - Path=/search-service/api-docs/json
          filters:
            - StripPrefix=1
        #결제 서버 swagger
        - id: payment-server-swagger
          uri: lb://PAYMENT-SERVER
          predicates:
            - Path=/payment-service/api-docs/json
          filters:
            - StripPrefix=1
        #알림 서버 swagger
        - id: notification-server-swagger
          uri: lb://NOTIFICATION-SERVER
          predicates:
            - Path=/notification-service/api-docs/json
          filters:
            - StripPrefix=1
        #종목 토론방(chat) 서버 swagger
        - id: stock-chat-server-swagger
          uri: lb://STOCK-CHAT-SERVER
          predicates:
            - Path=/stock-chat-service/api-docs/json
          filters:
            - StripPrefix=1

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    urls[0]:
      name: 매수매도 서비스
      url: /trade-service/api-docs/json
    urls[1]:
      name: 회원 서비스
      url: /member-service/api-docs/json
    urls[2]:
      name: 차트 서비스
      url: /chart-service/api-docs/json
    urls[3]:
      name: 검색 서비스
      url: /search-service/api-docs/json
    urls[4]:
      name: 결제 및 지갑 서비스
      url: /payment-service/api-docs/json
    urls[5]:
      name: 알림 서비스
      url: /notification-service/api-docs/json
    urls[6]:
      name: 종목 토론방(Chat) 서비스
      url: /stock-chat-service/api-docs/json

    use-root-path: true

#eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: gateway-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URl}

#Token
JWT:
  SECRET_KEY: sldkfjsoidfjwoeir12393012809vxcv89usdfkjn1203491iu0isdfl

server:
  port: ${GATEWAY_SERVER}